sudo: required

language: c

os: linux

dist: trusty

compiler: arm-none-eabi-gcc

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded

install:
  - wget https://github.com/stateos/IntrOS/archive/master.zip -O IntrOS-master.zip
  - unzip -q -d . IntrOS-master.zip IntrOS-master/IntrOS/kernel/*
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/
  - unzip -q -d . IntrOS-master.zip IntrOS-master/IntrOS/port/CORTEXM/*
  - mv -T IntrOS-master/IntrOS/port/CORTEXM/ IntrOS/port/CORTEXM/ 

before_script: arm-none-eabi-gcc --version

script: make all GNUCC=arm-none-eabi- -f makefile.gnucc

group: stable
