os: linux
sudo: required
language: generic

install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded
  - arm-none-eabi-gcc --version

before_script:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv IntrOS-master/IntrOS/* IntrOS/
  - rm -r IntrOS-master

script: make all GNUCC=arm-none-eabi- -f makefile.gnucc
